export const Channels = {
  TOGGLE_MAIN: "TOGGLE_MAIN",
  CLOSE_MAIN: "CLOSE_MAIN",
  SET_PIN_STATE: "SET_PIN_STATE",
  GET_PIN_STATE: "GET_PIN_STATE",
  PIN_STATE_UPDATED: "PIN_STATE_UPDATED"
  ,
  SCREENSHOT_UPDATED: "SCREENSHOT_UPDATED"
} as const;
